### PR TITLE
Change QrCode Route

### LINKED ISSUE #49: Generate secret route not found
Hi,

I just installed the plugin and followed the install instructions in the README. When I try to setup 2FA by clicking on the "Click me to get started button" i get the following error: 

```
No route found for \"GET https://<domain>/api/rl-2fa/generate-secret\" (from \"https://<domain>/admin\
```
When i debug the router I do see a route to generate the secret, among others: 

```
/api/v{version}/rl-2fa/generate-secret
```
Is there something I am missing during the installation?

### PR DESCRIPTION
**Pull request by WorksDev**
- fixes #49

### CODE REVIEW

**Comment by tinect** [comment]
In the issue are two different issues reported. Which one is this fixing?
Could you please explain how to reproduce the issue you are solving here?

**Comment by WorksDev** [comment]
hi @tinect,

the PR solves both problems - for some reason the route will not be resolved if there is a .png or .something at the end - in these cases the backend says the route could not be found, and the frontend shows an image placeholder without QR code data. 

I'm not sure if this is a problem on the web server side, or on the Shopware side (Apache2 & Nginx both give the same result) with a Shopware version v6.6

**Comment by tinect** [comment]
Sadly, I am unable to reproduce these issues in Shopware 6.6. :-(

**Comment by runelaenen** [comment]
Hi @WorksDev 
I will be closing this PR as this issue cannot be reproduced and it sounds to be an issue with the configuration of your webserver. Symfony/Shopware _should_ be able to handle any routes, whatever the extension is in the path.

**Pull request closed without merging**
